version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ticketnow_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ticketnow_db
      POSTGRES_USER: ticketnow_user
      POSTGRES_PASSWORD: ticketnow321

  pgadmin:
    image: dpage/pgadmin4
    container_name: ticketnow_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
